server.port=8089
spring.application.name=ms-promotores

spring.datasource.url=jdbc:mysql://localhost:3306/db_promotores?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

ms.ventas.url=http://localhost:8084

logging.level.com.ticket_system.promotores=DEBUG
logging.level.org.springframework.web=INFO
