server.port=8086
spring.application.name=ms-artistas

# MySQL DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/db_artistas?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# URL microservicio eventos #RESOLVER ESTE PROBLEMA
# ms.eventos.url=http://localhost:8081  

# Logging
logging.level.com.ticket_system=DEBUG
logging.level.org.springframework.web=INFO