server.port=8088
spring.application.name=ms-devoluciones

# MySQL DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/db_devoluciones?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# URLs de otros microservicios
ms.ventas.url=http://localhost:8084
ms.tickets.url=http://localhost:8083

# Logging
logging.level.com.ticket_system=DEBUG
logging.level.org.springframework.web=INFO